// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {Reclaim} from "@reclaimprotocol/verifier-solidity-sdk/contracts/Reclaim.sol";

/**
 * @title ITweetVerifier
 * @dev Interface for verifying tweet data
 */
interface ITweetVerifier {
    /**
     * @notice Verifies a Reclaim proof for a specific tweet ID.
     * @param tweetId The ID of the tweet this proof *should* be for.
     * @param reclaimProof The proof object generated by Reclaim.
     * @return hasNote True if the proof indicates a community note was found, false otherwise.
     * @dev Reverts if the proof is invalid or for the wrong tweet URL.
     */
    function verify(
        string memory tweetId,
        Reclaim.Proof memory reclaimProof
    ) external view returns (bool hasNote);
}
